// Code generated by mockery. DO NOT EDIT.
// © Daniil-Sakharov 2025
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// OrderHTTPConfig is an autogenerated mock type for the OrderHTTPConfig type
type OrderHTTPConfig struct {
	mock.Mock
}

type OrderHTTPConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderHTTPConfig) EXPECT() *OrderHTTPConfig_Expecter {
	return &OrderHTTPConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *OrderHTTPConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderHTTPConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type OrderHTTPConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *OrderHTTPConfig_Expecter) Address() *OrderHTTPConfig_Address_Call {
	return &OrderHTTPConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *OrderHTTPConfig_Address_Call) Run(run func()) *OrderHTTPConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfig_Address_Call) Return(_a0 string) *OrderHTTPConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfig_Address_Call) RunAndReturn(run func() string) *OrderHTTPConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// IdleTimeout provides a mock function with no fields
func (_m *OrderHTTPConfig) IdleTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdleTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHTTPConfig_IdleTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleTimeout'
type OrderHTTPConfig_IdleTimeout_Call struct {
	*mock.Call
}

// IdleTimeout is a helper method to define mock.On call
func (_e *OrderHTTPConfig_Expecter) IdleTimeout() *OrderHTTPConfig_IdleTimeout_Call {
	return &OrderHTTPConfig_IdleTimeout_Call{Call: _e.mock.On("IdleTimeout")}
}

func (_c *OrderHTTPConfig_IdleTimeout_Call) Run(run func()) *OrderHTTPConfig_IdleTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfig_IdleTimeout_Call) Return(_a0 time.Duration) *OrderHTTPConfig_IdleTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfig_IdleTimeout_Call) RunAndReturn(run func() time.Duration) *OrderHTTPConfig_IdleTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTimeout provides a mock function with no fields
func (_m *OrderHTTPConfig) ReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHTTPConfig_ReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTimeout'
type OrderHTTPConfig_ReadTimeout_Call struct {
	*mock.Call
}

// ReadTimeout is a helper method to define mock.On call
func (_e *OrderHTTPConfig_Expecter) ReadTimeout() *OrderHTTPConfig_ReadTimeout_Call {
	return &OrderHTTPConfig_ReadTimeout_Call{Call: _e.mock.On("ReadTimeout")}
}

func (_c *OrderHTTPConfig_ReadTimeout_Call) Run(run func()) *OrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfig_ReadTimeout_Call) Return(_a0 time.Duration) *OrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfig_ReadTimeout_Call) RunAndReturn(run func() time.Duration) *OrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTimeout provides a mock function with no fields
func (_m *OrderHTTPConfig) WriteTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WriteTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHTTPConfig_WriteTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTimeout'
type OrderHTTPConfig_WriteTimeout_Call struct {
	*mock.Call
}

// WriteTimeout is a helper method to define mock.On call
func (_e *OrderHTTPConfig_Expecter) WriteTimeout() *OrderHTTPConfig_WriteTimeout_Call {
	return &OrderHTTPConfig_WriteTimeout_Call{Call: _e.mock.On("WriteTimeout")}
}

func (_c *OrderHTTPConfig_WriteTimeout_Call) Run(run func()) *OrderHTTPConfig_WriteTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHTTPConfig_WriteTimeout_Call) Return(_a0 time.Duration) *OrderHTTPConfig_WriteTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHTTPConfig_WriteTimeout_Call) RunAndReturn(run func() time.Duration) *OrderHTTPConfig_WriteTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderHTTPConfig creates a new instance of OrderHTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHTTPConfig {
	mock := &OrderHTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
