services:
  postgres-order:
    image: postgres:17-alpine3.22

    container_name: postgres-order

    env_file:
      - .env

    volumes:
      - postgres_order_data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  postgres_order_data:

networks:
  microservices-net:
    external: true