// Code generated by ogen, DO NOT EDIT.

package order_v1

// setDefaults set default value of fields.
func (s *GetOrderResponse) setDefaults() {
	{
		val := OrderStatus("PENDING_PAYMENT")
		s.Status = val
	}
	{
		val := PaymentMethod("UNKNOWN")
		s.PaymentMethod.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PayOrderRequest) setDefaults() {
	{
		val := PaymentMethod("UNKNOWN")
		s.PaymentMethod = val
	}
}
