// Code generated by mockery. DO NOT EDIT.
// © Daniil-Sakharov 2025
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AssemblyConsumerService is an autogenerated mock type for the AssemblyConsumerService type
type AssemblyConsumerService struct {
	mock.Mock
}

type AssemblyConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyConsumerService) EXPECT() *AssemblyConsumerService_Expecter {
	return &AssemblyConsumerService_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function with given fields: ctx
func (_m *AssemblyConsumerService) RunConsumer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssemblyConsumerService_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type AssemblyConsumerService_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AssemblyConsumerService_Expecter) RunConsumer(ctx interface{}) *AssemblyConsumerService_RunConsumer_Call {
	return &AssemblyConsumerService_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *AssemblyConsumerService_RunConsumer_Call) Run(run func(ctx context.Context)) *AssemblyConsumerService_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AssemblyConsumerService_RunConsumer_Call) Return(_a0 error) *AssemblyConsumerService_RunConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AssemblyConsumerService_RunConsumer_Call) RunAndReturn(run func(context.Context) error) *AssemblyConsumerService_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssemblyConsumerService creates a new instance of AssemblyConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyConsumerService {
	mock := &AssemblyConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
