// Code generated by mockery. DO NOT EDIT.
// © Daniil-Sakharov 2025
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Daniil-Sakharov/RocketFactory/order/internal/model/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderProducerService is an autogenerated mock type for the OrderProducerService type
type OrderProducerService struct {
	mock.Mock
}

type OrderProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderProducerService) EXPECT() *OrderProducerService_Expecter {
	return &OrderProducerService_Expecter{mock: &_m.Mock}
}

// PublishOrderPaid provides a mock function with given fields: ctx, event
func (_m *OrderProducerService) PublishOrderPaid(ctx context.Context, event *domain.OrderProduceEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrderProduceEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderProducerService_PublishOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderPaid'
type OrderProducerService_PublishOrderPaid_Call struct {
	*mock.Call
}

// PublishOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.OrderProduceEvent
func (_e *OrderProducerService_Expecter) PublishOrderPaid(ctx interface{}, event interface{}) *OrderProducerService_PublishOrderPaid_Call {
	return &OrderProducerService_PublishOrderPaid_Call{Call: _e.mock.On("PublishOrderPaid", ctx, event)}
}

func (_c *OrderProducerService_PublishOrderPaid_Call) Run(run func(ctx context.Context, event *domain.OrderProduceEvent)) *OrderProducerService_PublishOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OrderProduceEvent))
	})
	return _c
}

func (_c *OrderProducerService_PublishOrderPaid_Call) Return(_a0 error) *OrderProducerService_PublishOrderPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderProducerService_PublishOrderPaid_Call) RunAndReturn(run func(context.Context, *domain.OrderProduceEvent) error) *OrderProducerService_PublishOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderProducerService creates a new instance of OrderProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducerService {
	mock := &OrderProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
